import { Metadata } from "next";
import Head from "next/head"

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function About() {
    return <div>
    <Head>
      <link rel="icon" href="../favicon.ico" />
    </Head>
    <h1>О нас</h1>
    </div>

  }